#intention: figure out how I want to style this stuff
import manim as mn
from manim import *
config.media_width = "75%"
config.verbosity = "WARNING"
print(mn.__version__)
manim --quality=h Big10FTC1
class Big10FTC1(Scene):
    def construct(self):
        banner = ManimBanner()
        self.play(banner.create())
        self.play(banner.expand())
        self.wait()
        self.play(Unwrite(banner))
        self.wait(2)
        np1 = NumberPlane(
            x_range = (-5,7,1),
            y_range = (-3,3,1),
            x_length = 12,
            y_length = 5
        )
        xvals = [-4,-2,0,2,6]
        yvals = [0,2,2,-2,2]
        self.play(Create(np1, run_time=3, lag_ratio=0.1))
        graph1 = np1.plot_line_graph(
            x_values=xvals,
            y_values=yvals,
            line_color=BLUE
        )
        label = MathTex(r"f(x)")
        label.move_to([-1,0,0])
        self.wait(1)
        self.play(Create(graph1, run_time=4),Write(label))
        self.wait(2)
        graphstuff = VGroup(np1,graph1,label)
        graphtarget = graphstuff.copy()
        graphtarget.width = 7
        graphtarget.to_corner(UL)
        self.play(Transform(graphstuff,graphtarget))
        self.wait(2)
        trap1 = Polygon(np1.coords_to_point(-4,0),np1.coords_to_point(-2,2),np1.coords_to_point(-2,0), color=YELLOW, fill_opacity=0.5)
        trap2 = Polygon(np1.coords_to_point(-2,0),np1.coords_to_point(-2,2),np1.coords_to_point(0,2),np1.coords_to_point(0,0), color=YELLOW, fill_opacity=0.5)
        trap3 = Polygon(np1.coords_to_point(0,0),np1.coords_to_point(0,2),np1.coords_to_point(1,0), color=YELLOW, fill_opacity = 0.5)
        trap4 = Polygon(np1.coords_to_point(2,-2),np1.coords_to_point(4,0),np1.coords_to_point(1,0), color=YELLOW, fill_opacity = 0.5)
        trap5 = Polygon(np1.coords_to_point(4,0),np1.coords_to_point(6,2),np1.coords_to_point(6,0), color=YELLOW, fill_opacity = 0.5)
        t1l = MathTex(r"2")
        t2l = MathTex(r"4")
        t3l = MathTex(r"1")
        t4l = MathTex(r"-3")
        t5l = MathTex(r"2")
        t1l.move_to(trap1.get_center())
        t2l.move_to(trap2.get_center())
        t3l.move_to(trap3.get_center())
        t4l.move_to(trap4.get_center())
        t5l.move_to(trap5.get_center())
        info = MathTex(r"g(x)=x+\int_{0}^{x}\!f(t)~dt")
        info.to_corner(UR)
        self.play(Write(info))
        self.wait(2)
        question = MathTex(r"Find~g'(-2)=",r"3")
        question.next_to(np1,DOWN)
        self.play(Write(question[0]))
        explanation1p1 = MathTex(r"g(x)=x+\int_{0}^{x}\!f(t)~dt")
        explanation1p1.next_to(question,DOWN)
        explanation1p2 = MathTex(r"g'(x)=1+",r"f(x)")
        explanation1p3 = MathTex(r"g'(-2)=1+",r"f(-2)")
        explanation1p2.move_to(explanation1p1)
        explanation1p3.move_to(explanation1p2)
        explanation1p4 = MathTex(r"g'(-2)=1+",r"2")
        explanation1p4.move_to(explanation1p3)
        explanation1p5 = MathTex(r"3")
        explanation1p5.move_to(explanation1p4)
        self.wait(2)
        self.play(Write(explanation1p1))
        self.wait(1)
        self.play(Transform(explanation1p1,explanation1p2))
        self.add(explanation1p2)
        self.remove(explanation1p1)
        self.wait(1)
        self.play(Transform(explanation1p2,explanation1p3))
        self.add(explanation1p3)
        self.remove(explanation1p2)
        self.wait(1)
        self.play(Transform(explanation1p3,explanation1p4))
        self.wait(1)
        self.play(Transform(explanation1p3,explanation1p5))
        self.add(explanation1p5)
        self.remove(explanation1p3)
        self.wait(1)
        self.play(Transform(explanation1p5,question[1]))
        self.wait(2)
        self.add(question[1])
        self.remove(explanation1p5)
        self.play(Unwrite(question))
        self.wait(1)
        question = MathTex(r"Find~g(6)=",r"6")
        question.next_to(np1,DOWN)
        self.play(Write(question[0]))
        explanation2p1 = MathTex(r"g(x)=x+\int_{0}^{x}\!f(t)~dt")
        explanation2p1.next_to(question,DOWN)
        explanation2p2 = MathTex(r"g(6)=6+",r"\int_{0}^{6}\!f(t)~dt")
        explanation2p2.move_to(explanation2p1)
        self.wait(2)
        self.play(Write(explanation2p1))
        self.wait(1)
        self.play(TransformMatchingShapes(explanation2p1,explanation2p2))
        self.add(explanation2p2)
        self.remove(explanation2p1)
        box = SurroundingRectangle(explanation2p2[1],buff=0.1)
        self.wait(0.5)
        self.play(Create(box))
        self.wait(1)
        trapgroup = VGroup(trap3,trap4,trap5)
        traplabelgroup = VGroup(t3l,t4l,t5l)
        self.play(DrawBorderThenFill(trapgroup))
        self.play(Write(traplabelgroup))
        self.wait(2)
        explanation2p3 = MathTex(r"1",r"+",r"-3",r"+",r"2")
        explanation2p3.next_to(explanation2p2,DOWN)
        explanation2p3g = VGroup(explanation2p3[1],explanation2p3[3])
        explanation2p3gn = VGroup(explanation2p3[0],explanation2p3[2],explanation2p3[4])
        self.play(Write(explanation2p3g))
        self.wait(1)
        self.play(Transform(traplabelgroup,explanation2p3gn))
        self.wait(0.5)
        self.add(explanation2p3gn)
        self.remove(traplabelgroup)
        self.play(Uncreate(trapgroup))
        explanation2p4 = MathTex(r"1-3+2")
        explanation2p4.move_to(explanation2p3)
        self.play(Transform(explanation2p3,explanation2p4))
        self.add(explanation2p4)
        self.remove(explanation2p3)
        self.wait(0.5)
        explanation2p5 = MathTex(r"2-2")
        explanation2p5.move_to(explanation2p4)
        self.play(Transform(explanation2p4,explanation2p5))
        self.add(explanation2p5)
        self.remove(explanation2p4)
        self.wait(0.5)
        explanation2p6 = MathTex(r"0")
        explanation2p6.move_to(explanation2p5)
        self.play(Transform(explanation2p5,explanation2p6))
        self.add(explanation2p6)
        self.remove(explanation2p5)
        self.wait(0.5)
        explanation2p7 = MathTex(r"g(6)=6+",r"0")
        explanation2p7.move_to(explanation2p2)
        self.play(Transform(explanation2p2,explanation2p7[0]),Uncreate(box))
        self.play(Transform(explanation2p6,explanation2p7[1]))
        self.add(explanation2p7)
        self.remove(explanation2p2)
        self.remove(explanation2p6)
        self.wait(0.5)
        explanation2p8 = MathTex(r"g(6)=6")
        explanation2p8.move_to(explanation2p7)
        self.play(Transform(explanation2p7,explanation2p8))
        self.add(explanation2p8)
        self.remove(explanation2p7)
        self.wait(0.5)
        self.play(Transform(explanation2p8,question[1]))
        self.add(question[1])
        self.remove(explanation2p8)
        self.wait(2)
        self.play(Unwrite(question))
        question = MathTex(r'''Find~g"(-1)=''',r"0")
        question.next_to(np1,DOWN)
        self.play(Write(question[0]))
        self.wait(2)
        explanation3p1 = MathTex(r"g(x)=x+\int_{0}^{x}\!f(t)~dt")
        explanation3p1.next_to(question,DOWN)
        explanation3p2 = MathTex(r"g'(x)=1+f(x)")
        explanation3p2.move_to(explanation3p1)
        explanation3p3 = MathTex(r'''g"(x)=f'(x)''')
        explanation3p3.move_to(explanation3p2)
        self.play(Write(explanation3p1))
        self.wait(0.5)
        self.play(Transform(explanation3p1,explanation3p2))
        self.wait(0.5)
        self.play(Transform(explanation3p1,explanation3p3))
        self.add(explanation3p3)
        self.remove(explanation3p1)
        self.wait(0.5)
        xvalsprime = [-4,-2,-2,0,0,2,2,6]
        yvalsprime = [1,1,0,0,-2,-2,1,1]
        graph2 = np1.plot_line_graph(
            x_values=xvalsprime,
            y_values=yvalsprime,
            line_color=RED
        )
        self.play(Create(graph2))
        self.wait(2)
        explanation3p4 = MathTex(r'''g"(-1)=f'(-1)''')
        explanation3p4.move_to(explanation3p3)
        self.play(Transform(explanation3p3,explanation3p4))
        self.add(explanation3p4)
        self.remove(explanation3p3)
        self.wait(0.5)
        point = Dot(point=np1.coords_to_point(-1,0),color=YELLOW)
        self.play(Create(point))
        explanation3p5 = MathTex(r'''g"(-1)=0''')
        explanation3p5.move_to(explanation3p4)
        self.play(Transform(explanation3p4,explanation3p5),Uncreate(point),Uncreate(graph2))
        self.add(explanation3p5)
        self.remove(explanation3p4)
        self.wait(0.5)
        self.play(Transform(explanation3p5,question[1]))
        self.add(question[1])
        self.remove(explanation3p5)
        self.wait(2)
        self.play(Unwrite(question))
        self.play(Unwrite(info))
        self.play(Uncreate(graphstuff,run_time=4))
        self.wait(2)
%%manim -qm Big10FTC2
class Big10FTC2(Scene):
    def construct(self):
        np = NumberPlane(
            x_range = (-4,6,1),
            y_range = (-2,4,1),
            x_length = 10,
            y_length = 6
        )
        firstline = Line(np.coords_to_point(-3,3),np.coords_to_point(1,3),color=BLUE)
        secondline = Line(np.coords_to_point(1,-1),np.coords_to_point(5,-1),color=BLUE)
        dot1 = Dot(point = np.coords_to_point(-3,3),color=WHITE)
        dot2 = Circle(color=WHITE, radius=0.08, fill_opacity=0)
        dot2.move_to(np.coords_to_point(1,3))
        dot3 = Dot(point = np.coords_to_point(1,-1),color=WHITE)
        dot4 = Dot(point = np.coords_to_point(5,-1),color=WHITE)
        self.play(Create(np,run_time=2))
        label = MathTex(r"f(x)")
        label.move_to(np.coords_to_point(2,1))
        graph = VGroup(firstline,secondline,dot1,dot2,dot3,dot4,label)
        self.play(Create(graph,run_time=2))
        graphstuff = VGroup(np,graph)
        graphtarget = graphstuff.copy()
        graphtarget.width = 7
        graphtarget.to_edge(UP)
        self.wait(2)
        self.play(Transform(graphstuff,graphtarget))
        self.wait(0.5)
        question = MathTex(r"Average~value~of~f(x)~on~[-3,5]=",r"1")
        question.next_to(np,DOWN)
        self.play(Write(question[0]))
        self.wait(2)
        explanation1p1 = MathTex(r"\frac{1}{5-(-3)}\int_{-3}^{5}\!f(x)~dx")
        explanation1p1.next_to(question,DOWN)
        self.play(Write(explanation1p1))
        self.wait(0.5)
        explanation1p2 = MathTex(r"\frac{1}{8}\int_{-3}^{5}\!f(x)~dx")
        explanation1p2.move_to(explanation1p1)
        self.play(Transform(explanation1p1,explanation1p2))
        self.add(explanation1p2)
        self.remove(explanation1p1)
        self.wait(0.5)
        rect1 = Polygon(np.coords_to_point(-3,3),np.coords_to_point(1,3),np.coords_to_point(1,0),np.coords_to_point(-3,0),color=YELLOW, fill_opacity=0.5)
        rect2 = Polygon(np.coords_to_point(1,-1),np.coords_to_point(1,0),np.coords_to_point(5,0),np.coords_to_point(5,-1),color=YELLOW, fill_opacity=0.5)
        rl1 = MathTex(r"12")
        rl2 = MathTex(r"-4")
        rl1.move_to(rect1.get_center())
        rl2.move_to(rect2.get_center())
        areagroup = VGroup(rect1,rect2)
        labelgroup = VGroup(rl1,rl2)
        self.play(DrawBorderThenFill(areagroup))
        self.play(Write(labelgroup))
        self.wait(2)
        explanation1p3 = MathTex(r"\frac{1}{8}",r"(",r"12",r"+",r"-4",r")")
        explanation1p3.move_to(explanation1p2)
        ex3g1 = VGroup(explanation1p3[0],explanation1p3[1],explanation1p3[3],explanation1p3[5])
        self.play(Transform(explanation1p2,ex3g1))
        self.add(ex3g1)
        self.remove(explanation1p2)
        self.wait(0.5)
        ex3g2 = VGroup(explanation1p3[2],explanation1p3[4])
        self.play(Transform(labelgroup,ex3g2))
        self.add(ex3g2)
        self.remove(labelgroup)
        self.play(Uncreate(areagroup))
        self.wait(0.5)
        self.add(explanation1p3)
        self.remove(ex3g1,ex3g2)
        explanation1p4 = MathTex(r"\frac{1}{8}8")
        explanation1p4.move_to(explanation1p3)
        self.play(Transform(explanation1p3,explanation1p4))
        self.add(explanation1p4)
        self.remove(explanation1p3)
        self.wait(0.5)
        explanation1p5 = MathTex(r"\frac{8}{8}")
        explanation1p6 = MathTex(r"1")
        explanation1p5.move_to(explanation1p4)
        explanation1p6.move_to(explanation1p5)
        self.play(Transform(explanation1p4,explanation1p5),Uncreate(areagroup))
        self.play(Transform(explanation1p4,explanation1p6))
        self.add(explanation1p6)
        self.remove(explanation1p4)
        self.wait(0.5)
        self.play(Transform(explanation1p6,question[1]))
        self.add(question[1])
        self.remove(explanation1p6)
        self.wait(2)
        self.play(Unwrite(question))
        self.play(Uncreate(graphstuff))
        self.wait(2)