#animate that one usub sheet
import manim as mn
from manim import *
config.media_width = "75%"
config.verbosity = "WARNING"
print(mn.__version__)
manim --quality=h uSubTest
%%manim -qm uSubTest
class uSubTest(Scene):
    def construct(self):
        banner = ManimBanner()
        self.play(banner.create())
        self.play(banner.expand())
        self.wait()
        self.play(Unwrite(banner))
        self.wait(2)
        questionfull = MathTex(r"\int_{0}^{3}\!2(2x-1)^{2}~dx=",r"42")
        question = questionfull[0].copy()
        questionfull.to_edge(UP)
        self.play(Write(question))
        self.play(question.animate.move_to(questionfull[0]))
        self.wait(2)
        self.add(questionfull[0])
        self.remove(question)
        explanation1p1 = MathTex(r"\int_{{{0}}}^{{{3}}}\!{{2(}}",r"2x-1",r"{{)^{2}~dx}}")
        explanation1p1.next_to(questionfull,DOWN)
        self.play(Write(explanation1p1))
        self.wait(0.5)
        brace = Brace(explanation1p1[6])
        u = MathTex(r"u")
        u.next_to(brace,DOWN)
        self.play(Write(brace))
        self.play(Write(u))
        self.wait(0.5)
        explanation1p2 = MathTex(r"du = 2dx")
        explanation1p2.next_to(u,DOWN)
        explanation1p3 = MathTex(r"\int_{{{x=0}}}^{{{x=3}}}\!{{2(}}",r"2x-1",r"{{)^{2}~dx}}")
        explanation1p3.move_to(explanation1p1)
        newbrace = Brace(explanation1p3[6])
        newu = u.copy()
        newu.next_to(newbrace,DOWN)
        self.play(TransformMatchingTex(explanation1p1,explanation1p3),Transform(brace,newbrace),Transform(u,newu),Write(explanation1p2))
        self.add(explanation1p3)
        self.remove(explanation1p1)
        self.wait(0.5)
        part = explanation1p3[6].copy()
        part2 = part.copy()
        explanation1p4 = MathTex(r"2(0)-1=-1")
        explanation1p4.next_to(explanation1p3,RIGHT)
        explanation1p42 = MathTex(r"2(3)-1=5")
        explanation1p42.next_to(explanation1p4,DOWN)
        self.play(Transform(part,explanation1p4),Transform(part2, explanation1p42))
        self.add(explanation1p4)
        self.add(explanation1p42)
        self.remove(part)
        self.remove(part2)
        explanation1p5 = MathTex(r"\int_{{{u=-1}}}^{{{u=5}}}\!{{u^{2}~dx}}")
        explanation1p5.move_to(explanation1p3)
        newbrace = Brace(explanation1p5[5])
        newu = u.copy()
        newu.next_to(newbrace,DOWN)
        self.play(Transform(explanation1p3,explanation1p5),Transform(brace,newbrace),Transform(u,newu))
        self.wait(0.5)
        part3 = explanation1p5.copy()
        explanation1p6 = MathTex(r"\frac{1}{3}u^{3}\biggr\rvert_{-1}^{5}")
        explanation1p6.next_to(explanation1p2,DOWN)
        self.play(Write(explanation1p6))
        self.wait(0.5)
        explanation1p7 = MathTex(r"\frac{125}{3}-\frac{-1}{3}=42")
        explanation1p7.next_to(explanation1p6,DOWN)
        copy = explanation1p6.copy()
        self.play(Transform(copy,explanation1p7))
        self.add(explanation1p7)
        self.remove(copy)
        box1 = SurroundingRectangle(explanation1p7,buff=0.1)
        box2 = SurroundingRectangle(questionfull[1],buff=0.1)
        copy = explanation1p7.copy()
        self.wait(0.5)
        self.play(Transform(copy,questionfull[1]),Create(box1),LaggedStart(Create(box2)))
        self.add(questionfull[1])
        self.remove(copy)
        self.wait(2)
        self.play(Uncreate(box1),Uncreate(box2))
        self.play(Unwrite(explanation1p7))
        self.play(Unwrite(explanation1p6))
        self.play(Unwrite(part3),Unwrite(u),Unwrite(explanation1p5),Unwrite(brace),Unwrite(part),Unwrite(part2),Unwrite(explanation1p3),Unwrite(explanation1p2),Unwrite(explanation1p4),Unwrite(explanation1p42))
        self.wait(2)
        self.play(Unwrite(questionfull))
        self.wait(2)
        questionfull = MathTex(r"\int_{\frac{\pi}{6}}^{\frac{\pi}{6}}\!2\sin(2\theta)~d\theta=", r"\frac{3}{2}")
        self.play(Write(questionfull))
        self.wait(2)