#animate that one usub sheet
import manim as mn
from manim import *
config.media_width = "75%"
config.verbosity = "WARNING"
print(mn.__version__)
manim --quality=h uSubTest
%%manim -qm uSubTest
class uSubTest(Scene):
    def construct(self):
        banner = ManimBanner()
        self.play(banner.create())
        self.play(banner.expand())
        self.wait()
        self.play(Unwrite(banner))
        self.wait(2)
        questionfull = MathTex(r"\int_{0}^{3}\!2(2x-1)^{2}~dx=",r"42")
        question = questionfull[0].copy()
        questionfull.to_edge(UP)
        self.play(Write(question))
        self.play(question.animate.move_to(questionfull[0]))
        self.wait(2)
        self.add(questionfull[0])
        self.remove(question)
        explanation1p1 = MathTex(r"\int_{{{0}}}^{{{3}}}\!{{2(}}",r"2x-1",r"{{)^{2}~dx}}")
        explanation1p1.next_to(questionfull,DOWN)
        self.play(Write(explanation1p1))
        self.wait(0.5)
        brace = Brace(explanation1p1[6])
        u = MathTex(r"u")
        u.next_to(brace,DOWN)
        self.play(Write(brace))
        self.play(Write(u))
        self.wait(0.5)
        explanation1p2 = MathTex(r"du = 2dx")
        explanation1p2.next_to(u,DOWN)
        explanation1p3 = MathTex(r"\int_{{{x=0}}}^{{{x=3}}}\!{{2(}}",r"2x-1",r"{{)^{2}~dx}}")
        explanation1p3.move_to(explanation1p1)
        newbrace = Brace(explanation1p3[6])
        newu = u.copy()
        newu.next_to(newbrace,DOWN)
        self.play(TransformMatchingTex(explanation1p1,explanation1p3),Transform(brace,newbrace),Transform(u,newu),Write(explanation1p2))
        self.add(explanation1p3)
        self.remove(explanation1p1)
        self.wait(0.5)
        part = explanation1p3[6].copy()
        part2 = part.copy()
        explanation1p4 = MathTex(r"2(0)-1=-1")
        explanation1p42 = MathTex(r"2(3)-1=5")
        explanation1p42.next_to(explanation1p3,RIGHT)
        explanation1p4.next_to(explanation1p42,DOWN)
        self.play(Transform(part,explanation1p4),Transform(part2, explanation1p42))
        self.add(explanation1p4)
        self.add(explanation1p42)
        self.remove(part)
        self.remove(part2)
        explanation1p5 = MathTex(r"\int_{{{u=-1}}}^{{{u=5}}}\!{{u^{2}}}{{~dx}}")
        explanation1p5.move_to(explanation1p3)
        newbrace = Brace(explanation1p5[5])
        newu = u.copy()
        newu.next_to(newbrace,DOWN)
        self.play(Transform(explanation1p3,explanation1p5),Transform(brace,newbrace),Transform(u,newu))
        self.wait(0.5)
        part3 = explanation1p5.copy()
        explanation1p6 = MathTex(r"\frac{1}{3}u^{3}\biggr\rvert_{-1}^{5}")
        explanation1p6.next_to(explanation1p2,DOWN)
        self.play(Write(explanation1p6))
        self.wait(0.5)
        explanation1p7 = MathTex(r"\frac{125}{3}-\frac{-1}{3}=42")
        explanation1p7.next_to(explanation1p6,DOWN)
        copy = explanation1p6.copy()
        self.play(Transform(copy,explanation1p7))
        self.add(explanation1p7)
        self.remove(copy)
        box1 = SurroundingRectangle(explanation1p7,buff=0.1)
        box2 = SurroundingRectangle(questionfull[1],buff=0.1)
        copy = explanation1p7.copy()
        self.wait(0.5)
        self.play(Transform(copy,questionfull[1]),Create(box1),LaggedStart(Create(box2)))
        self.add(questionfull[1])
        self.remove(copy)
        self.wait(2)
        self.play(Uncreate(box1),Uncreate(box2))
        self.play(Unwrite(explanation1p7))
        self.play(Unwrite(explanation1p6))
        self.play(Unwrite(part3),Unwrite(u),Unwrite(brace),Unwrite(explanation1p3),Unwrite(explanation1p2),Unwrite(explanation1p4),Unwrite(explanation1p42))
        self.wait(2)
        self.play(Unwrite(questionfull))
        self.wait(2)
        questionfull = MathTex(r"\int_{\frac{\pi}{6}}^{\frac{\pi}{2}}\!2\sin(2\theta)~d\theta=", r"\frac{3}{2}")
        questionfull.to_edge(UP)
        question = questionfull[0].copy()
        question.move_to(ORIGIN)
        self.play(Write(question))
        self.wait(1)
        self.play(question.animate.move_to(questionfull[0]))
        self.add(questionfull[0])
        self.remove(question)
        explanation2p1 = MathTex(r"\int_{{{\frac{\pi}{6}}}}^{{{\frac{\pi}{2}}}}\!2\sin({{2\theta}})~{{d\theta}}")
        explanation2p1.next_to(questionfull,DOWN)
        brace = Brace(explanation2p1[5])
        u = MathTex(r"u")
        u.next_to(brace,DOWN)
        self.play(Write(explanation2p1))
        self.wait(1)
        self.play(LaggedStart(Write(brace),Write(u),lag_ratio=0.5))
        self.wait(0.5)
        explanation2p2 = MathTex(r"du = 2d\theta")
        explanation2p2.next_to(u,DOWN)
        explanation2p3 = MathTex(r"\int_{{{\theta=\frac{\pi}{6}}}}^{{{\theta=\frac{\pi}{2}}}}\!2\sin({{2\theta}})~{{d\theta}}")
        explanation2p3.move_to(explanation2p1)
        newbrace = Brace(explanation2p3[5])
        self.play(Write(explanation2p2),Transform(explanation2p1,explanation2p3),Transform(brace,newbrace),u.animate.next_to(newbrace,DOWN))
        self.add(explanation2p3)
        self.remove(explanation2p1)
        self.wait(0.5)
        part1 = explanation2p1[5].copy()
        part2 = part1.copy()
        lowlim = MathTex(r"\frac{\pi}{6}\times2=",r"\frac{\pi}{3}")
        upplim = MathTex(r"\frac{\pi}{2}\times2=",r"\pi")
        upplim.next_to(explanation2p1,RIGHT)
        lowlim.next_to(upplim,DOWN)
        self.play(LaggedStart(Transform(part1,upplim),Transform(part2,lowlim),lag_ratio=0.5))
        self.add(upplim)
        self.add(lowlim)
        self.remove(part1)
        self.remove(part2)
        self.wait(0.5)
        explanation2p4 = MathTex(r"\int_{{{u=\frac{\pi}{3}}}}^{{{u=\pi}}}\!\sin(u)~du")
        explanation2p4.move_to(explanation2p3)
        copy = lowlim[1].copy()
        copy1 = upplim[1].copy()
        self.play(Transform(explanation2p3,explanation2p4),Transform(copy,explanation2p4[1]),Transform(copy1,explanation2p4[2]),Unwrite(lowlim),Unwrite(upplim),Unwrite(u),Unwrite(brace))
        self.remove(copy)
        self.remove(copy1)
        self.wait(0.5)
        explanation2p5 = MathTex(r"-\cos~u\biggr\rvert_{\frac{\pi}{3}}^{\pi}=",r"\frac{3}{2}")
        explanation2p5.next_to(explanation2p4,DOWN)
        explanation2p5p = explanation2p5[0].copy()
        self.play(Transform(explanation2p2,explanation2p5p))
        self.add(explanation2p5[0])
        self.remove(explanation2p2)
        self.remove(explanation2p5p)
        self.wait(0.5)
        box1 = SurroundingRectangle(explanation2p5[1],buff=0.1)
        box2 = SurroundingRectangle(questionfull[1],buff=0.1)
        self.play(Write(explanation2p5[1]))
        self.wait(1)
        copy = explanation2p5[1].copy()
        self.play(LaggedStart(Create(box1),Transform(copy,questionfull[1]),Create(box2),lag_ratio=1))
        self.add(questionfull[1])
        self.remove(copy)
        self.wait(2)
        self.play(Uncreate(box1),Uncreate(box2))
        self.play(LaggedStart(Unwrite(explanation2p5),Unwrite(explanation2p3),lag_ratio=0.75))
        self.wait(2)
        self.play(Unwrite(questionfull))
        self.wait(2)
        questionfull = MathTex(r"\int_{-1}^{2}\!3x^{2}(2-x^{3})^{4}~dx=",r"\frac{8019}{5}")
        questionfull.to_edge(UP)
        question = questionfull[0].copy()
        question.move_to(ORIGIN)
        self.play(Write(question))
        self.wait(1)
        self.play(question.animate.move_to(questionfull[0]))
        self.add(questionfull[0])
        self.remove(question)
        self.wait(2)
        explanation3p1 = MathTex(r"\int_{{{-1}}}^{{{2}}}\!3x^{2}{{(2-x^{3})}}^{4}~dx")
        explanation3p1.next_to(questionfull,DOWN)
        self.play(Write(explanation3p1))
        self.wait(0.5)
        explanation3p2 = MathTex(r"\int_{{{x=-1}}}^{{{x=2}}}\!3x^{2}{{(2-x^{3})}}^{4}~dx")
        explanation3p2.move_to(explanation3p1)
        brace = Brace(explanation3p2[5])
        u = MathTex(r"u")
        u.next_to(brace,DOWN)
        self.play(LaggedStart(Transform(explanation3p1,explanation3p2),Write(brace),Write(u),lag_ratio=0.5))
        self.add(explanation3p2)
        self.remove(explanation3p1)
        self.wait(0.5)
        du = MathTex(r"du = 3x^{2}dx")
        du.next_to(u,DOWN)
        self.play(Write(du))
        copy1 = explanation3p2[5].copy()
        copy2 = copy1.copy()
        lowlim = MathTex(r"2-(-1)^{3}=3")
        upplim = MathTex(r"2-(2)^{3}=-6")
        upplim.next_to(explanation3p2,RIGHT)
        lowlim.next_to(upplim,DOWN)
        self.play(LaggedStart(Transform(copy1,upplim),Transform(copy2,lowlim),lag_ratio=0.5))
        self.add(upplim)
        self.add(lowlim)
        self.remove(copy1)
        self.remove(copy2)
        self.wait(1)
        explanation3p3 = MathTex(r"\int_{{{u=3}}}^{{{u=-6}}}\!u^{4}~du")
        explanation3p3.move_to(explanation3p2)
        self.play(Unwrite(u),Unwrite(brace),Transform(lowlim,explanation3p3[2]),Transform(upplim,explanation3p3[1]),Transform(explanation3p2,explanation3p3))
        self.add(explanation3p3)
        self.remove(explanation3p2)
        self.remove(lowlim)
        self.remove(upplim)
        self.wait(2)